# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-12 06:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='type',
            field=models.CharField(choices=[('Perfect(192)', '192'), ('Charming(219)', '219'), ('Elegant(238)', '238'), ('Luxury(267)', '267')], max_length=20),
        ),
    ]
