# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-07 03:20
from __future__ import unicode_literals

from django.db import migrations, models
import welcome.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='본 포스팅의 제목을 입력해주세요.', max_length=100, validators=[welcome.models.min_length_10_validators], verbose_name='제목')),
                ('content', models.TextField(verbose_name='상세 내용')),
                ('photo', models.ImageField(upload_to='progress/%Y/%m/%d')),
                ('status', models.CharField(choices=[('d', 'Draft'), ('p', 'Published'), ('w', 'Withdrawn')], max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='progress',
            name='tag_set',
            field=models.ManyToManyField(blank=True, to='welcome.Tag'),
        ),
    ]
