# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-07 16:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welcome', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('57', 'Simple'), ('65', 'Harmonious'), ('68', 'Perfect'), ('77', 'Luxury')], max_length=2)),
                ('address', models.CharField(help_text='A-1과 같은 형식으로 입력해주세요', max_length=3, unique=True)),
                ('total_land', models.IntegerField()),
                ('your_land', models.IntegerField()),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='House_Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='house',
            name='house_tag_set',
            field=models.ManyToManyField(blank=True, to='welcome.House_Tag'),
        ),
    ]
