# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-07 17:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welcome', '0002_auto_20171008_0116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='type',
            field=models.CharField(choices=[('Simple(57)', '57'), ('Harmonious(65)', '65'), ('Perfect(68)', '68'), ('Luxury(77)', '77')], max_length=20),
        ),
    ]
