# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-09 13:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welcome', '0003_auto_20171008_0236'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='hero_image/%Y/%m/%d')),
            ],
        ),
    ]
