# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-09 14:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welcome', '0005_heroimage_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='heroimage',
            name='content',
            field=models.CharField(default='서해안을 바라보는 명품 단독형 주거단지', max_length=100),
        ),
        migrations.AddField(
            model_name='heroimage',
            name='title',
            field=models.CharField(default='PRECIOUS', max_length=50),
        ),
    ]
