# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-10 04:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('welcome', '0006_auto_20171009_2357'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='house',
            name='house_tag_set',
        ),
        migrations.RemoveField(
            model_name='progress',
            name='tag_set',
        ),
        migrations.DeleteModel(
            name='House',
        ),
        migrations.DeleteModel(
            name='House_Tag',
        ),
        migrations.DeleteModel(
            name='Progress',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
