# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-11 15:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
        ('welcome', '0007_auto_20171010_1347'),
    ]

    operations = [
        migrations.CreateModel(
            name='Welcome_House',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='welcome_house', to='dashboard.House', verbose_name='house')),
            ],
        ),
    ]
