# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-11 15:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
        ('welcome', '0008_welcome_house'),
    ]

    operations = [
        migrations.CreateModel(
            name='House1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='address1', to='dashboard.House', verbose_name='address')),
                ('house_tag_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='house_tag_set1', to='dashboard.House', verbose_name='house_tag_set')),
                ('price', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price1', to='dashboard.House', verbose_name='price')),
                ('total_land', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='total_land1', to='dashboard.House', verbose_name='total_land')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='type1', to='dashboard.House', verbose_name='type')),
                ('your_land', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='your_land1', to='dashboard.House', verbose_name='your_land')),
            ],
        ),
        migrations.RemoveField(
            model_name='welcome_house',
            name='field',
        ),
        migrations.DeleteModel(
            name='Welcome_House',
        ),
    ]
