# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-12 06:12
from __future__ import unicode_literals

from django.db import migrations, models
import phonenumber_field.modelfields
import welcome.models


class Migration(migrations.Migration):

    dependencies = [
        ('welcome', '0009_auto_20171012_0040'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, validators=[welcome.models.min_length_10_validators], verbose_name='예약자')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(help_text='연락 가능하신 번호를 0100000000 형태로 입력해주세요.', max_length=128, verbose_name='연락처')),
                ('email', models.EmailField(max_length=254, verbose_name='이메일주소')),
                ('address', models.CharField(help_text='주소지를 적어주시면 캠핑카 분양상담 예약에 도움을 받으실 수 있습니다.', max_length=100, verbose_name='주소지')),
                ('date', models.DateTimeField(blank=True, verbose_name='가능한 날짜')),
                ('detail', models.TextField(blank=True, verbose_name='참고할 사항')),
                ('detail_admin', models.TextField(blank='True', verbose_name='예약 손님에 대한 정보를 입력하는 란')),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('r', '문의작성완료'), ('c', '캠핑카분양상담예약'), ('s', '현장방문상담예약')], max_length=1)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.RemoveField(
            model_name='house1',
            name='address',
        ),
        migrations.RemoveField(
            model_name='house1',
            name='house_tag_set',
        ),
        migrations.RemoveField(
            model_name='house1',
            name='price',
        ),
        migrations.RemoveField(
            model_name='house1',
            name='total_land',
        ),
        migrations.RemoveField(
            model_name='house1',
            name='type',
        ),
        migrations.RemoveField(
            model_name='house1',
            name='your_land',
        ),
        migrations.DeleteModel(
            name='House1',
        ),
    ]
