# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-12 13:47
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welcome', '0011_auto_20171012_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='date',
            field=models.DateField(blank=True, help_text='2018-01-03 와 같은 형식으로 입력해주세요. 더 많은 일시의 목록은 하단의 추가사항에 입력해주세요.', verbose_name='상담가능일'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='detail',
            field=models.TextField(blank=True, verbose_name='추가사항'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='phone_number',
            field=models.CharField(help_text='연락 가능하신 번호를 빈칸없는 형태로 입력해주세요.', max_length=15, validators=[django.core.validators.RegexValidator(message='8자에서 15자의 숫자를 빈칸없이 입력하여 주세요.', regex='^\\d{8,15}$')], verbose_name='연락처'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('r', '문의작성완료'), ('v', '찾아가는상담예약중'), ('s', '현장방문상담예약중'), ('c', '상담완료')], default='r', max_length=1),
        ),
    ]
