# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-17 15:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welcome', '0012_auto_20171012_2247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='date',
            field=models.DateField(blank='True', help_text='2018-01-03 와 같은 형식으로 입력해주세요. 더 많은 날짜는 하단의 추가사항에 입력해주세요.', verbose_name='상담예약일'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='detail',
            field=models.TextField(blank=True, help_text='문의사항, 상담 가능 날짜 및 관심있는 타입(예시: B타입)을 적어주세요', verbose_name='추가사항'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('r', '상담예약대기중'), ('v', '찾아가는상담예약중'), ('s', '현장방문상담예약중'), ('c', '상담완료')], default='r', max_length=1),
        ),
    ]
