# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-18 01:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welcome', '0015_auto_20171018_1031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='date',
            field=models.DateField(default='1111-11-11', help_text='2018-01-03 와 같은 형식으로 입력해주세요. 더 많은 날짜는 하단의 추가사항에 입력해주세요.', verbose_name='상담예약일'),
        ),
    ]
