# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-18 04:56
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welcome', '0016_auto_20171018_1035'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='corporate',
            field=models.CharField(blank=True, help_text='(선택항목)법인 구매 상담을 위해 필요한 항목입니다,', max_length=30, verbose_name='법인명'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='preferred_type',
            field=models.CharField(blank=True, choices=[('A', 'A 타입(192)'), ('B', 'B 타입(219)'), ('C', 'C 타입(238)'), ('D', 'D 타입(267)')], help_text='(선택항목/다수선택가능)관심있는 타입을 작성해주세요', max_length=10),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='address',
            field=models.CharField(blank=True, help_text='(선택항목)주소지를 적어주시면 찾아가는 분양상담 예약에 도움을 받으실 수 있습니다.', max_length=100, verbose_name='주소지'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='date',
            field=models.DateField(blank=True, help_text='2018-01-03 와 같은 형식으로 입력해주세요. 더 많은 날짜는 하단의 추가사항에 입력해주세요.', verbose_name='상담예약일'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='detail',
            field=models.TextField(blank=True, help_text='(선택항목)문의사항 및 상담 가능 날짜를 적어주세요.', verbose_name='추가사항'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='email',
            field=models.EmailField(help_text='분양 정보 제공 및 상담 이외의 목적으로 사용되지 않습니다.', max_length=254, verbose_name='이메일주소'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='name',
            field=models.CharField(help_text='실명 혹은 닉네임을 입력해주세요', max_length=10, verbose_name='예약자'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='phone_number',
            field=models.CharField(help_text='연락 가능하신 번호를 빈칸없는 형태로 입력해주세요. 분양 정보 제공 및 상담 이외의 목적으로 사용되지 않습니다.', max_length=15, validators=[django.core.validators.RegexValidator(message='8자에서 15자의 숫자를 빈칸없이 입력하여 주세요.', regex='^\\d{8,15}$')], verbose_name='연락처'),
        ),
    ]
