# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-18 06:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welcome', '0017_auto_20171018_1356'),
    ]

    operations = [
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='(선택항목/다수선택가능)관심있는 타입을 작성해주세요', max_length=20, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='preferred_type',
        ),
        migrations.AddField(
            model_name='reservation',
            name='type_set',
            field=models.ManyToManyField(blank=True, to='welcome.Type'),
        ),
    ]
