# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-18 11:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('welcome', '0019_auto_20171018_1654'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='password',
        ),
    ]
